### ISSUE TITLE
Unsure about any_msgs and elevation_change_msgs dependency for traversability_checker

### ISSUE THREAD

**Issue by nznobody** [leggedrobotics/traversability_estimation#27]
Hello,

I have been unable to build the traversability_checker package due to dependencies on:

any_msgs
elevation_change_msgs

I have tried to search where these dependencies could be resolved from but the internet seems to come up dry. Am I missing something obvious? Are they supposed to be generated by a package?

I have installed:
Linux tegra-ubuntu 3.10.67 (Jetson TX1)
ROS Jade
Kindr 1.0.0 & 0.0.1 (Because elevation_mapping depends on 0.0.1)
grid_map (SHA f4489a41bbefdeeb7b99a94574bfadb058cfb73e)
elevation_map (SHA bd5893b6dc27e8e00b5bd67b8282e6358de30cca)
sm_common and sm_timing build from source with catkin (SHA a7dba60d51feb6073724030b3e2a5e2f483e6a53)

The rest all builds fine.

Regards,
Manu

**Comment by martiwer** [comment]
Hi Manu

No, this dependencies are not obvious. The elevation_change_msgs can be found on the branch feature/obstacle_detection at the repository [elevation_mapping](https://github.com/ethz-asl/elevation_mapping/tree/feature/obstacle_detection). This branch also depends on kindr 1.0.0. Any_msgs are internal dependencies from our lab and not public. If you want to use this node you have to modify the code and remove everything related to any_msgs.

However, we will possibly move the traversability_checker node to a different repository, as it is more designed for our internal use only. For using the traversability estimation you don't need to run this node. Therefore, I assume you don't need to build it.

Best
Martin
