### ISSUE TITLE
service [/traversability_estimation/save_to_bag] responded with an error: Time is out of dual 32-bit range

### ISSUE THREAD

**Issue by wojiaojiao** [leggedrobotics/traversability_estimation#37]
when i:rosservice call /traversability_estimation/save_to_bag 

ERROR: service [/traversability_estimation/save_to_bag] responded with an error: Time is out of dual 32-bit range

how can i solve it?

**Comment by martiwer** [comment]
Hi @wojiaojiao,
I couldn't reproduce your error. But I fixed the path for saving the bag file, such that you can now specify it in the launch file. Have a look here #39 . Additionally there is now an example elevation map for loading and saving.
