### ISSUE TITLE
migration to ROS2 Humble

### ISSUE THREAD

**Issue by er1c-cartman** [leggedrobotics/traversability_estimation#81]
Hi
first, thanks for sharing your amazing work
I've tried your package on ROS1 noetic environment and it worked well
Now I'm trying to use on ROS2 humble environment, and is there any plans or some works that have done to use on ROS2 humble environment?
Best regards

**Comment by nimiCurtis** [comment]
Hi @er1c-cartman Is there any progress on this matter? Have you successfully transferred this package to ROS2? I assume it hinges on the availability of the ROS2 version for elevation_map, which I'm uncertain about its existence.

Thanks

**Comment by er1c-cartman** [comment]
yes... that's the problem
i have to migrate elevation mapping and related packages first, but unfortunately due to my lacking skills, it doesn't have any progress...
so wanted to know and find some other ppl's work on migration but still searching for it :)
if u have some progress or related work, it would be really awesome to share it
best regards

**Comment by Muhammad540** [comment]
I have ported the traversability estimation package to ROS2 Humble, you can access it here : https://github.com/Muhammad540/traversability_estimation
