### ISSUE TITLE
Ported `traversability_estimation` to ROS2 Humble

### ISSUE THREAD

**Issue by Muhammad540** [leggedrobotics/traversability_estimation#84]
Hi,

I have successfully ported the `traversability_estimation` package to ROS2 Humble. The ported version is available in my repository https://github.com/Muhammad540/traversability_estimation

The port includes:
- Conversion of all source files and dependencies to ROS2 Humble.
- Updated `package.xml` and `CMakeLists.txt`.
- Verification and testing on ROS2 Humble.

I believe this port will be beneficial to the community, and I would like to make it available for everyone. I want to thank the authors of the traversability_estimation package for their excellent work, which has made this port possible.

Thank you.

**Comment by Muhammad540** [comment]
> Hi,
> 
> I have successfully ported the `traversability_estimation` package to ROS2 Humble. The ported version is available in my repository https://github.com/Muhammad540/traversability_estimation
> 
> The port includes:
> 
> * Conversion of all source files and dependencies to ROS2 Humble.
> * Updated `package.xml` and `CMakeLists.txt`.
> * Verification and testing on ROS2 Humble.
> 
> I believe this port will be beneficial to the community, and I would like to make it available for everyone. I want to thank the authors of the traversability_estimation package for their excellent work, which has made this port possible.
> 
> Thank you.

I have also ported the elevation mapping package to ROS2, however it is not a complete port of the package but just enough to get started. It is available here: https://github.com/Muhammad540/elevation_mapping.git

**Comment by salmagro** [comment]
Was this merged already to the upstream repo? I can not see any `ros2`  or `humble` branch.

**Comment by Muhammad540** [comment]
> Was this merged already to the upstream repo? I can not see any `ros2` or `humble` branch.

I should have clarified earlier – the port to ROS2 Humble was done in a slightly unconventional way. Instead of following the typical process, I created a manual fork and made the necessary modifications to just get it working in ROS2. Unfortunately, i did not had enough time to open a PR and structure the code perfectly :disappointed:

However, you can get it up and running, checkout the package here [ROS2 Humble Traversability Estimation](https://github.com/Muhammad540/traversability_estimation ) Please feel free to give it a try, and I’d be happy to assist if you have any questions or suggestions.
